"""
Pydantic models for form specifications.

⚠️  AUTO-GENERATED FROM JSON SCHEMA - DO NOT EDIT MANUALLY
Source: src/joget_form_generator/schema/form_spec_schema.json
Regenerate: python scripts/generate_models.py
"""

# generated by datamodel-codegen:
#   filename:  form_spec_schema.json
#   timestamp: 2025-11-10T12:06:46+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class FormMetadata(BaseModel):
    id: str = Field(..., max_length=20, pattern='^[a-zA-Z][a-zA-Z0-9_]{0,19}$')
    """
    Form ID (must match tableName, max 20 chars)
    """
    name: str = Field(..., max_length=255, min_length=1)
    """
    Human-readable form name displayed in Joget
    """
    tableName: str | None = Field(None, max_length=20, pattern='^[a-zA-Z][a-zA-Z0-9_]{0,19}$')
    """
    Database table name (must match id)
    """
    description: str | None = None
    """
    Optional form description
    """


class Type(Enum):
    """
    Field type (Phase 1: 9 standard, Phase 2: 4 custom/advanced, Enterprise: 4 advanced fields)
    """

    hiddenField = 'hiddenField'
    textField = 'textField'
    passwordField = 'passwordField'
    textArea = 'textArea'
    selectBox = 'selectBox'
    checkBox = 'checkBox'
    radio = 'radio'
    datePicker = 'datePicker'
    fileUpload = 'fileUpload'
    customHTML = 'customHTML'
    idGenerator = 'idGenerator'
    subform = 'subform'
    grid = 'grid'
    calculationField = 'calculationField'
    richTextEditor = 'richTextEditor'
    formGrid = 'formGrid'
    multiPagedForm = 'multiPagedForm'


class Size(Enum):
    """
    Field size
    """

    small = 'small'
    medium = 'medium'
    large = 'large'


class Option(BaseModel):
    value: str
    """
    Option value (stored in database)
    """
    label: str
    """
    Option label (displayed to user)
    """


class Type1(Enum):
    """
    Options source type
    """

    formData = 'formData'
    api = 'api'
    database = 'database'


class Method(Enum):
    """
    HTTP method (api type)
    """

    GET = 'GET'
    POST = 'POST'


class OptionsSource(BaseModel):
    type: Type1
    """
    Options source type
    """
    formId: str | None = None
    """
    Source form ID (formData type)
    """
    valueColumn: str | None = 'id'
    """
    Column for option value
    """
    labelColumn: str | None = 'name'
    """
    Column for option label
    """
    parentField: str | None = None
    """
    Parent field ID for cascading dropdown
    """
    filterField: str | None = None
    """
    Field to filter by in cascading dropdown
    """
    extraCondition: str | None = None
    """
    Additional SQL WHERE condition
    """
    url: AnyUrl | None = None
    """
    API endpoint URL (api type)
    """
    method: Method | None = 'GET'
    """
    HTTP method (api type)
    """
    valueJsonPath: str | None = None
    """
    JSONPath for value extraction (api type)
    """
    labelJsonPath: str | None = None
    """
    JSONPath for label extraction (api type)
    """


class Validation(BaseModel):
    pattern: str | None = None
    """
    Regex pattern for validation
    """
    minLength: int | None = Field(None, ge=0)
    """
    Minimum character length
    """
    maxLength: int | None = Field(None, ge=1)
    """
    Maximum character length
    """
    message: str | None = None
    """
    Custom validation error message
    """


class FieldModel(BaseModel):
    id: str = Field(..., max_length=50, pattern='^[a-zA-Z][a-zA-Z0-9_]*$')
    """
    Field ID (database column name)
    """
    label: str = Field(..., min_length=1)
    """
    Field label shown in UI
    """
    type: Type
    """
    Field type (Phase 1: 9 standard fields)
    """
    required: bool | None = False
    """
    Whether field is mandatory
    """
    readonly: bool | None = False
    """
    Whether field is read-only
    """
    defaultValue: str | None = None
    """
    Default value for field
    """
    placeholder: str | None = None
    """
    Placeholder text (textField, textArea, passwordField)
    """
    size: Size | None = 'medium'
    """
    Field size
    """
    rows: int | None = Field(None, ge=1, le=50)
    """
    Number of rows (textArea)
    """
    cols: int | None = Field(None, ge=1, le=200)
    """
    Number of columns (textArea)
    """
    maxlength: int | None = Field(None, ge=1)
    """
    Maximum character length
    """
    options: list[Option] | None = Field(None, min_length=1)
    """
    Static options (selectBox, checkBox, radio)
    """
    optionsSource: OptionsSource | None = None
    """
    Dynamic options configuration
    """
    multiple: bool | None = False
    """
    Allow multiple selections (selectBox, checkBox)
    """
    dateFormat: str | None = 'yyyy-MM-dd'
    """
    Date format pattern (datePicker)
    """
    maxSize: int | None = None
    """
    Maximum file size in MB (fileUpload)
    """
    fileTypes: str | None = None
    """
    Allowed file extensions, comma-separated (fileUpload)
    """
    validation: Validation | None = None
    """
    Validation rules
    """


class JogetFormSpecification(BaseModel):
    """
    Schema for Joget DX form definitions in canonical YAML format
    """

    form: FormMetadata
    fields: list[FieldModel] = Field(..., min_length=1)
