"""
Pydantic models for form specifications.

⚠️  AUTO-GENERATED FROM JSON SCHEMA - DO NOT EDIT MANUALLY
Source: src/joget_form_generator/schema/form_spec_schema.json
Regenerate: python scripts/generate_models.py
"""

# generated by datamodel-codegen:
#   filename:  form_spec_schema.json
#   timestamp: 2025-12-17T16:51:48+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class FormMetadata(BaseModel):
    id: str = Field(..., max_length=20, pattern='^[a-zA-Z][a-zA-Z0-9_]{0,19}$')
    """
    Form ID (must match tableName, max 20 chars)
    """
    name: str = Field(..., max_length=255, min_length=1)
    """
    Human-readable form name displayed in Joget
    """
    tableName: str | None = Field(None, max_length=20, pattern='^[a-zA-Z][a-zA-Z0-9_]{0,19}$')
    """
    Database table name (must match id)
    """
    description: str | None = None
    """
    Optional form description
    """


class Type(Enum):
    """
    Field type (Phase 1: 9 standard, Phase 2: 4 custom/advanced, Enterprise: 4 advanced, Structural: section)
    """

    hiddenField = 'hiddenField'
    textField = 'textField'
    passwordField = 'passwordField'
    textArea = 'textArea'
    selectBox = 'selectBox'
    checkBox = 'checkBox'
    radio = 'radio'
    datePicker = 'datePicker'
    fileUpload = 'fileUpload'
    customHTML = 'customHTML'
    idGenerator = 'idGenerator'
    subform = 'subform'
    grid = 'grid'
    calculationField = 'calculationField'
    richTextEditor = 'richTextEditor'
    formGrid = 'formGrid'
    multiPagedForm = 'multiPagedForm'
    section = 'section'


class Size(Enum):
    """
    Field size (full = 100% width)
    """

    small = 'small'
    medium = 'medium'
    large = 'large'
    full = 'full'


class Editor(Enum):
    """
    Rich text editor type (richTextEditor)
    """

    tinymce = 'tinymce'
    quill = 'quill'


class Option(BaseModel):
    value: str
    """
    Option value (stored in database)
    """
    label: str
    """
    Option label (displayed to user)
    """


class Type1(Enum):
    """
    Options source type
    """

    formData = 'formData'
    api = 'api'
    database = 'database'


class RequestType(Enum):
    """
    HTTP request method (api type)
    """

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    DELETE = 'DELETE'


class PostMethod(Enum):
    """
    POST/PUT body format (api type)
    """

    parameters = 'parameters'
    jsonPayload = 'jsonPayload'
    custom = 'custom'


class Param(BaseModel):
    name: str | None = None
    value: str | None = None


class Header(BaseModel):
    name: str | None = None
    value: str | None = None


class OptionsSource(BaseModel):
    type: Type1
    """
    Options source type
    """
    formId: str | None = None
    """
    Source form ID (formData type)
    """
    valueColumn: str | None = 'id'
    """
    Column for option value (formData, database)
    """
    labelColumn: str | None = 'name'
    """
    Column for option label (formData, database)
    """
    groupingColumn: str | None = None
    """
    Column for option grouping
    """
    parentField: str | None = None
    """
    Parent field ID for cascading dropdown
    """
    filterField: str | None = None
    """
    Field to filter by in cascading dropdown
    """
    addEmptyOption: bool | None = True
    """
    Add empty first option (formData, api)
    """
    emptyLabel: str | None = ''
    """
    Label for empty option
    """
    useAjax: bool | None = False
    """
    Use AJAX for loading options
    """
    jsonUrl: AnyUrl | None = None
    """
    API endpoint URL (api type)
    """
    requestType: RequestType | None = 'GET'
    """
    HTTP request method (api type)
    """
    postMethod: PostMethod | None = 'parameters'
    """
    POST/PUT body format (api type)
    """
    params: list[Param] | None = None
    """
    Request parameters (api type)
    """
    customPayload: str | None = None
    """
    Custom JSON payload (api type, postMethod=custom)
    """
    headers: list[Header] | None = None
    """
    HTTP headers (api type)
    """
    idColumn: str | None = None
    """
    JSON field for value (api type)
    """
    multirowBaseObject: str | None = None
    """
    Base JSON object path for array extraction (api type)
    """
    jdbcDatasource: str | None = 'default'
    """
    JDBC datasource name (database type)
    """
    tableName: str | None = None
    """
    Database table name (database type)
    """
    extraCondition: str | None = None
    """
    SQL WHERE condition (database type)
    """
    addEmpty: bool | None = True
    """
    Add empty first option (database type)
    """


class Validation(BaseModel):
    pattern: str | None = None
    """
    Regex pattern for validation
    """
    minLength: int | None = Field(None, ge=0)
    """
    Minimum character length
    """
    maxLength: int | None = Field(None, ge=1)
    """
    Maximum character length
    """
    message: str | None = None
    """
    Custom validation error message
    """


class FormatType(Enum):
    """
    Column display format type
    """

    text = 'text'
    options = 'options'
    date = 'date'


class GridColumn(BaseModel):
    value: str
    """
    Field ID from child form to display in column
    """
    label: str
    """
    Column header label
    """
    formatType: FormatType | None = 'text'
    """
    Column display format type
    """
    format: str | None = ''
    """
    Format pattern (for date columns)
    """
    width: str | None = ''
    """
    Column width (e.g., '100px', '20%')
    """


class Page(BaseModel):
    formId: str
    """
    Referenced form ID for this page
    """
    label: str | None = None
    """
    Page label/title
    """
    description: str | None = None
    """
    Page description
    """


class FieldModel(BaseModel):
    id: str = Field(..., max_length=50, pattern='^[a-zA-Z][a-zA-Z0-9_]*$')
    """
    Field ID (database column name)
    """
    label: str = Field(..., min_length=1)
    """
    Field label shown in UI
    """
    type: Type
    """
    Field type (Phase 1: 9 standard, Phase 2: 4 custom/advanced, Enterprise: 4 advanced, Structural: section)
    """
    required: bool | None = False
    """
    Whether field is mandatory
    """
    readonly: bool | None = False
    """
    Whether field is read-only
    """
    defaultValue: str | None = None
    """
    Default value for field
    """
    placeholder: str | None = None
    """
    Placeholder text (textField, textArea, passwordField)
    """
    size: Size | None = 'medium'
    """
    Field size (full = 100% width)
    """
    rows: int | None = Field(None, ge=1, le=50)
    """
    Number of rows (textArea)
    """
    cols: int | None = Field(None, ge=1, le=200)
    """
    Number of columns (textArea)
    """
    maxlength: int | None = Field(None, ge=1)
    """
    Maximum character length
    """
    options: list[Option] | None = Field(None, min_length=1)
    """
    Static options (selectBox, checkBox, radio)
    """
    optionsSource: OptionsSource | None = None
    """
    Dynamic options configuration
    """
    multiple: bool | None = False
    """
    Allow multiple selections (selectBox, checkBox)
    """
    dateFormat: str | None = 'yyyy-MM-dd'
    """
    Date format pattern (datePicker)
    """
    maxSize: int | None = None
    """
    Maximum file size in MB (fileUpload)
    """
    fileTypes: str | None = None
    """
    Allowed file extensions, comma-separated (fileUpload)
    """
    html: str | None = None
    """
    HTML content (customHTML)
    """
    prefix: str | None = None
    """
    ID prefix (idGenerator)
    """
    postfix: str | None = None
    """
    ID postfix (idGenerator)
    """
    format: str | None = None
    """
    ID format pattern, e.g., '{prefix}{count:05d}{postfix}' (idGenerator)
    """
    formId: str | None = None
    """
    Referenced form ID (subform)
    """
    columns: list[GridColumn] | None = None
    """
    Grid column definitions (grid, formGrid)
    """
    equation: str | None = None
    """
    Calculation equation/formula (calculationField)
    """
    storeNumeric: bool | None = True
    """
    Store result as numeric value (calculationField)
    """
    editor: Editor | None = 'tinymce'
    """
    Rich text editor type (richTextEditor)
    """
    allowAddRow: bool | None = True
    """
    Allow adding new rows (formGrid)
    """
    allowDeleteRow: bool | None = True
    """
    Allow deleting rows (formGrid)
    """
    validateMinRow: int | None = Field(None, ge=0)
    """
    Minimum number of rows (grid, formGrid)
    """
    validateMaxRow: int | None = Field(None, ge=1)
    """
    Maximum number of rows (grid, formGrid)
    """
    errorMessage: str | None = None
    """
    Custom error message for grid validation (grid, formGrid)
    """
    pages: list[Page] | None = Field(None, min_length=1)
    """
    Page definitions (multiPagedForm)
    """
    showNavigation: bool | None = True
    """
    Show page navigation (multiPagedForm)
    """
    showProgressBar: bool | None = True
    """
    Show progress bar (multiPagedForm)
    """
    validation: Validation | None = None
    """
    Validation rules
    """


class JogetFormSpecification(BaseModel):
    """
    Schema for Joget DX form definitions in canonical YAML format
    """

    form: FormMetadata
    fields: list[FieldModel] = Field(..., min_length=1)
